apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  schemaVersion: v1.0.0
  name: superpowers
  description: Forked from https://github.com/obra/superpowers
  annotations:
    github.com/project-slug: Bandwidth/superpowers
  organization: BW
  costCenter: undefined
  platformType: AWS
  buildPlatform: GitHub Actions
spec:
  type: Utility
  owner: github/band-cx
  lifecycle: Prototype
  dependsOn:
    - resource:platform/GitHub Actions
    - resource:cost-center/undefined
